name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0+1
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  http: ^1.4.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^10.2.3
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path_android: "assets/icons/android.png"
  image_path_ios: "assets/icons/ios.png"  
  android: true
  ios: true
  remove_alpha_ios: true
  
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/google_fonts/